config/routes.rb
Rails.application.routes.draw do
  resources :teams

  resources :people
  resources :laps
  resources :widgets

  root 'ranking#index'
  
  post '/inbound' => 'griddler/emails#create'

  post '/laps/checkin/:id' => 'laps#checkin', as: 'lap_checkin'
  post '/laps/checkout/:id' => 'laps#checkout', as: 'lap_checkout'
  

end

app/models/person.rb
require 'digest/md5'

class Person < ActiveRecord::Base
  has_many :laps, dependent: :destroy
  belongs_to :team, inverse_of: :people

  
  def avatar_url
    photo_url == "" && gravatar_url || photo_url
  end
  
  def gravatar_url
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end
  
  def <<
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy, :check_in]

  # GET /people
  # GET /people.json
  def index
    @people = Person.order(:name)
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    @teams = Team.all
  end

  # GET /people/1/edit
  def edit
    @teams = Team.all
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
#        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.html { redirect_to people_url, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #POST /people/checkin/1
  def checkin
    @lap=Lap.new(started_at: Time.now)
    @person.laps << lap
    @person.save

    respond_to do |format|
      format.js
    end
  end
  
  #POST /people/checkout/1
  def checkout
    @person.laps.first
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :photo_url, :team_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="row collapse">
	<%= form_for(@person) do |f| %>
  <div class="small-12 large-10 columns">
    <%= f.text_field :name, placeholder: 'piloto' %>
    <%= f.collection_select(:team_id, @teams, :id, :name,  include_blank: 'Selecione a equipe')%>
    <%= f.text_field :email, placeholder: 'irn' %>
    <%= f.text_field :photo_url, placeholder: 'Telefone' %>
	  <%= f.submit 'Gravar', class: "button prefix"%>
  </div>
	<% end %>
</div>

app/views/people/_ranking.erb
<h4>Pilotos mais econômicos</h4>
  <table>
    <tbody>
      <tr>
        <th class="small-2 large-2 center">Consumo médio</th>
        <th>Piloto</th>
      </tr>
      <% @drivers.each do |driver| %>
        <tr>
          <td class="small-2 large-2"><%= driver.average_consumption %> </td>
          <td><%= driver.person.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<h4>Menções honrosas</h4>
<h6>Velocidade média</h6>
<table>
  <tbody>
    <tr>
      <th class="small-2 large-2 center">Velocidade</th>
      <th>Piloto</th>
    </tr>
    <% @fastest.each do |driver| %>
      <tr>
        <td class="small-2 large-2"><%= driver.average_speed %> </td>
        <td><%= driver.person.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h6>Distância s/ consumo</h6>
<table>
  <tbody>
    <tr>
      <th class="small-2 large-2 center">Distância</th>
      <th>Piloto</th>
    </tr>
    <% @without_consumption.each do |driver| %>
      <tr>
        <td class="small-2 large-2"><%= driver.without_consumption %> </td>
        <td><%= driver.person.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
	

app/views/people/edit.html.erb
<div class="row">
	<div class="small-9 columns">
    <h2>Piloto</h2>
	</div>
	<div class="small-3 columns">
	  <%= link_to 'voltar', people_path, class: "small button prefix" %>
  </div>
	<%= render 'form' %>


<!--    <div class="actions">
    	<%= button_to 'Destroy', {action: :destroy, id: @person.id, data: { confirm: 'Tem certeza? Todas as voltas deste piloto seráo apagadas.'}}, 
    	  	  { method: :delete, class: 'button alert' } %></td>
    </div>
-->    
</div>

app/views/people/index.html.erb
<div class="row">
    <div class="small-12 large-10">
<h1>Pilotos</h1>

<% @people.each do |person| %>
<ul class="vcard large-3 small-12">
		<li class="fn"><%= link_to person.name, person_path(person) %></li>
		<li class="email"><%= person.team.name %></li>
<!--		<li><%= person.photo_url %></li> -->
</ul>
<% end %>

<br>

<!--%= link_to 'New Person', new_person_path, class:"small button" %-->
</div>
</div>

app/views/people/new.html.erb
<div class="row">
    <div class="small-12 large-10">
        <h2>New person</h2>
				<%= link_to 'Back', people_path %>

<%= render 'form' %>

</div>
</div>

app/views/people/show.html.erb
<div class="row ">
	<div class="small-6 columns">
    <h2>Piloto</h2>
	</div>
	<div class="small-3 columns">
		<%= link_to 'Editar', edit_person_path(@person) , class: "small button prefix"%>
	</div>
	<div class="small-3 columns">
	  <%= link_to 'Voltar', people_path, class: "small button prefix" %>
  </div>
  <div class="small-12 large-10 columns">
	  <p><strong>Nome: </strong><%= @person.name %></p>
	  <p><strong>Equipe: </strong><%= @person.team.name %></p>
  </div>
</div>
<%= render 'laps/checkin'%>