config/routes.rb
Rails.application.routes.draw do
  resources :teams

  resources :people
  resources :laps
  resources :widgets

  root 'ranking#index'
  
  post '/inbound' => 'griddler/emails#create'

  post '/laps/checkin/:id' => 'laps#checkin', as: 'lap_checkin'
  post '/laps/checkout/:id' => 'laps#checkout', as: 'lap_checkout'
  

end

app/models/lap.rb
class Lap < ActiveRecord::Base
  belongs_to :person
  #before_save :update_attributes
  
  def << (message)
    @previous, @last = @last, message
    @first = message if @first.nil?
    update_attributes
  end

  def update_attributes
    self.distance = distance_traveled
    self.total_consumption - fuel_spent
  end

  private
  
    def fuel_spent
      @last.fuel_level_displayed - @first.fuel_level_displayed
    end

    def distance_traveled
      @last.distance_totalizer - @first.distance_totalizer
    end

end

app/controllers/lap_controller.rb
class LapController < ApplicationController
end

app/controllers/laps_controller.rb
class LapsController < ApplicationController
  before_action :set_lap, only: [:show, :edit, :update, :destroy, :checkout]

  # GET /laps
  # GET /laps.json
  def index
    @laps = Lap.joins(:person).order("people.name")
  end

  # GET /laps/1
  # GET /laps/1.json
  def show
  end

  # GET /laps/new
  def new
    @lap = Lap.new
  end

  # GET /laps/1/edit
  def edit
  end

  # POST /laps
  # POST /laps.json
  def create
    @lap = Lap.new(lap_params)

    respond_to do |format|
      if @lap.save
        format.html { redirect_to laps_url, notice: 'Lap was successfully created.' }
        format.json { render :show, status: :created, location: @lap }
      else
        format.html { render :new }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #POST /laps/checkin/1
  def checkin
    @lap=Lap.new(started_at: Time.now)
    @lap.person = Person.find(params[:id])
    @lap.save

    respond_to do |format|
      format.js
    end
  end
  
  #POST /laps/checkout/1
  def checkout
    @lap.finished_at = Time.now
    @lap.save
    respond_to do |format|
      format.html {redirect_to edit_lap_path(@lap)}
    end
  end


  # PATCH/PUT /laps/1
  # PATCH/PUT /laps/1.json
  def update
    respond_to do |format|
      if @lap.update(lap_params)
        format.html { redirect_to laps_url, notice: 'Lap was successfully updated.' }
        format.json { render :show, status: :ok, location: @lap }
      else
        format.html { render :edit }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laps/1
  # DELETE /laps/1.json
  def destroy
    @lap.destroy
    respond_to do |format|
      format.html { redirect_to laps_url, notice: 'Lap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lap
      @lap = Lap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lap_params
      params.require(:lap).permit(:person_id, :distance, :duration, :score, :acceleration, :gear_changes, :anticipation, :average_consumption, :total_consumption, :average_speed, :without_consumption, :started_at, :finished_at)
    end
end

app/helpers/lap_helper.rb
module LapHelper
end

app/helpers/laps_helper.rb
module LapsHelper
end

app/views/laps/_checkin.html.erb
<div class="row " id='checkin'>
	<div class="small-12 columns">
		<h4>Clique no botão checkin para registrar o início do percurso</h4>
		<%= form_tag (lap_checkin_path), method: :post, remote: true do %>
			<%= hidden_field_tag(:person_id, @person.id) %>
			<%= submit_tag 'Check-in', class: 'button sucess prefix'%>
			<% end %>
	</div>
</div>

app/views/laps/_checkout.html.erb
<div class="row " id='checkout'>
	<div class="small-12 columns">
		<h4>Ao final do percurso, informe o arquivo de dados e pressione o botão checkout.</h4>
	  <%= link_to 'Check-out', lap_checkout_path(id: @lap.id), remote: false, method: :post, class: "small button alert prefix" %>
	</div>
</div>

app/views/laps/_form.html.erb
<%= form_for(@lap) do |f| %>
<div class="row">
	<div class="small-6 columns">
	  <%= f.label :average_consumption, 'Consumo médio', class: ' inline' %><br>
	</div>
	<div class="small-5 columns">
	  <%= f.text_field :average_consumption %>
	</div>
</div>
<div class="row">
	<div class="small-5 columns">
	  <%= f.label :average_speed, 'Velocidade média', class: ' inline' %><br>
	</div>
	<div class="small-5 columns">
	  <%= f.text_field :average_speed %>
	</div>
</div>
<div class="row">
	<div class="small-5 columns">
	  <%= f.label :without_consumption, 'Distância s/ consumo', class: ' inline' %><br>
	</div>
	<div class="small-5 columns">
	  <%= f.text_field :without_consumption %>
	</div>
</div>
<div class="row">
	<div class="small-5 columns">
	  <%= f.label :acceleration, 'Aceleração', class: ' inline' %><br>
	</div>
	<div class="small-5 columns">
	  <%= f.text_field :acceleration %>
	</div>
</div>
<div class="row">
	<div class="small-5 columns">
    <%= f.label :gear_changes, 'Troca de marchas', class: ' inline' %><br>
  </div>
  <div class="small-5 columns">
    <%= f.text_field :gear_changes %>
  </div>
</div>
<div class="row">
	<div class="small-5 columns">
    <%= f.label :anticipation, 'Antecipação', class: ' inline' %><br>
  </div>
  <div class="small-5 columns">
    <%= f.text_field :anticipation %>
  </div>
</div>
<div class="row">
	<div class="small-5 columns">
	  <%= f.label :score, 'Score', class: ' inline'%><br>
	</div>
	<div class="small-5 columns">
	  <%= f.number_field :score %>
	</div>
</div>
<div class="row">
  <div class="small-12 columns">
    <%= f.submit 'Salvar', class: 'small-12 button'%>
  </div>
</div>



<% end %>

app/views/laps/_ranking.html.erb
<h4>Classificação final</h4>


<table >
  <thead>
    <tr>
      <th>Piloto</th>
			<th>Equipe</th>
      <th>Consumo médio</th>
      <th>Velocidade média</th>
      <th>Distância sem consumo</th>
      <th>Aceleração</th>
      <th>Troca de marchas</th>
      <th>Antecipação</th>
      <th>Eco Score</th>
    </tr>
  </thead>

  <tbody>
    <% @laps.each do |lap| %>
      <tr>
        <td><%= lap.person.name %></td>
        <td><%= lap.person.team.name %></td>
        <td><%= lap.average_consumption %></td>
        <td><%= lap.average_speed %></td>
        <td><%= lap.without_consumption %></td>
        <td><%= lap.acceleration %></td>
        <td><%= lap.gear_changes %></td>
        <td><%= lap.anticipation %></td>
        <td><%= lap.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/laps/checkin.js.erb
$('#checkin').fadeOut().empty().hide().prepend("<%= j render 'checkout'%>");
$('#checkin').fadeIn();

app/views/laps/edit.html.erb
<<h2>Dados do medianav</h2>

<%= render 'form' %>

app/views/laps/index.html.erb
<h2>Voltas mais recentes</h2>


<table>
  <thead>
    <tr>
      <th>Piloto</th>
      <th>Consumo médio</th>
      <th>Velocidade média</th>
      <th>Distância sem consumo</th>
      <th>Aceleração</th>
      <th>Troca de marchas</th>
      <th>Antecipação</th>
      <th>Eco Score</th>
    </tr>
  </thead>

  <tbody>
    <% @laps.each do |lap| %>
      <tr>
        <td><%= lap.person.name %></td>
        <td><%= lap.average_consumption %></td>
        <td><%= lap.average_speed %></td>
        <td><%= lap.without_consumption %></td>
        <td><%= lap.acceleration %></td>
        <td><%= lap.gear_changes %></td>
        <td><%= lap.anticipation %></td>
        <td><%= lap.score %></td>
        <td><%= link_to 'Edit', edit_lap_path(lap) %></td>
        <td><%= link_to 'Destroy', lap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/laps/new.html.erb
<h1>New lap</h1>

<%= render 'form' %>

<%= link_to 'Back', laps_path %>

app/views/laps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Distance:</strong>
  <%= @lap.distance %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @lap.duration %>
</p>

<p>
  <strong>Score:</strong>
  <%= @lap.score %>
</p>

<p>
  <strong>Acceleration:</strong>
  <%= @lap.acceleration %>
</p>

<p>
  <strong>Gear changes:</strong>
  <%= @lap.gear_changes %>
</p>

<p>
  <strong>Anticipation:</strong>
  <%= @lap.anticipation %>
</p>

<p>
  <strong>Average consumption:</strong>
  <%= @lap.average_consumption %>
</p>

<p>
  <strong>Total consumption:</strong>
  <%= @lap.total_consumption %>
</p>

<p>
  <strong>Average speed:</strong>
  <%= @lap.average_speed %>
</p>

<p>
  <strong>Without consumption:</strong>
  <%= @lap.without_consumption %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @lap.started_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @lap.finished_at %>
</p>

<%= link_to 'Edit', edit_lap_path(@lap) %> |
<%= link_to 'Back', laps_path %>