config/routes.rb
Rails.application.routes.draw do
  resources :teams

  resources :people
  resources :laps
  resources :widgets

  root 'ranking#index'
  
  post '/inbound' => 'griddler/emails#create'

  post '/laps/checkin/:id' => 'laps#checkin', as: 'lap_checkin'
  post '/laps/checkout/:id' => 'laps#checkout', as: 'lap_checkout'
  

end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/_index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      #tripmeter {
        border: 3px double black;
        padding: 10px;
        margin: 10px 0;
      }
      
      p {
        color: #222;
        font: 14px Arial;
      }
      
      span {
        color: #00C;
      }
    </style>
  </head>
  <body>
    <div id="tripmeter">
      <p>
        Starting Location (lat, lon):<br/>
        <span id="startLat">???</span>&deg;, <span id="startLon">???</span>&deg;
      </p>
      <p>
        Current Location (lat, lon):<br/>
        <span id="currentLat">???</span>&deg;, <span id="currentLon">???</span>&deg;
      </p>
      <p>
        Distance from starting location:<br/>
        <span id="distance">0</span> km
      </p>
    </div>
    <script>
      window.onload = function() {
        var startPos;
      
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            startPos = position;
            document.getElementById("startLat").innerHTML = startPos.coords.latitude;
            document.getElementById("startLon").innerHTML = startPos.coords.longitude;
          }, function(error) {
            alert("Error occurred. Error code: " + error.code);
            // error.code can be:
            //   0: unknown error
            //   1: permission denied
            //   2: position unavailable (error response from locaton provider)
            //   3: timed out
          });
      
          navigator.geolocation.watchPosition(function(position) {
            document.getElementById("currentLat").innerHTML = position.coords.latitude;
            document.getElementById("currentLon").innerHTML = position.coords.longitude;
            document.getElementById("distance").innerHTML =
              calculateDistance(startPos.coords.latitude, startPos.coords.longitude,
                                position.coords.latitude, position.coords.longitude);
          });
        }
      };
      
      // Reused code - copyright Moveable Type Scripts - retrieved May 4, 2010.
      // http://www.movable-type.co.uk/scripts/latlong.html
      // Under Creative Commons License http://creativecommons.org/licenses/by/3.0/
      function calculateDistance(lat1, lon1, lat2, lon2) {
        var R = 6371; // km
        var dLat = (lat2-lat1).toRad();
        var dLon = (lon2-lon1).toRad();
        var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
                Math.cos(lat1.toRad()) * Math.cos(lat2.toRad()) *
                Math.sin(dLon/2) * Math.sin(dLon/2);
        var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
        var d = R * c;
        return d;
      }
      Number.prototype.toRad = function() {
        return this * Math.PI / 180;
      }
    </script>
  </body>
</html>​

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>